#!/bin/bash
# =============================================================
# Step 6: Update Nginx — proxy /api/ to the Node API & remove
#         the old HTTP Basic Auth protection
# Run this script on your VPS as root (or with sudo)
# Usage: sudo bash 06_update_nginx_api.sh
# =============================================================

set -e

DOMAIN="cargo.neoaiaeon.com"
NGINX_CONF="/etc/nginx/sites-available/${DOMAIN}"
HOST_PORT=8080    # port the Docker frontend container listens on
API_PORT=3001     # port the Node API listens on

echo "======================================"
echo " A3 Cargo - Update Nginx for API"
echo "======================================"

# ── Back up the existing config first ────────────────────────────────────────
BACKUP="${NGINX_CONF}.bak.$(date +%Y%m%d_%H%M%S)"
cp "$NGINX_CONF" "$BACKUP"
echo "[1/3] Backed up existing config to ${BACKUP}"

# ── Write the new config (replaces existing) ─────────────────────────────────
echo "[2/3] Writing updated nginx config..."

# Read the SSL cert paths that certbot generated (they live in the existing conf)
SSL_CERT=$(grep -oP 'ssl_certificate\s+\K[^;]+' "$BACKUP" | head -1 || echo "")
SSL_KEY=$(grep -oP 'ssl_certificate_key\s+\K[^;]+' "$BACKUP" | head -1 || echo "")

# Build the server block. We keep the HTTP→HTTPS redirect and SSL config
# that certbot already added. We simply strip auth_basic and add /api/ proxy.
cat > "$NGINX_CONF" << NGINXEOF
# Managed by A3 Cargo deploy scripts
# Regenerated by 06_update_nginx_api.sh on $(date)

server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    server_name ${DOMAIN};

    # SSL — paths set by Certbot
    ssl_certificate     ${SSL_CERT:-/etc/letsencrypt/live/${DOMAIN}/fullchain.pem};
    ssl_certificate_key ${SSL_KEY:-/etc/letsencrypt/live/${DOMAIN}/privkey.pem};
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    # ── API proxy ─────────────────────────────────────────────────────────
    # Route /api/* to the local Node.js Express server.
    # NOTE: No auth_basic here — authentication is handled by JWT.
    location /api/ {
        proxy_pass         http://127.0.0.1:${API_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 30s;
    }

    # ── Frontend proxy ────────────────────────────────────────────────────
    # Route everything else to the Docker container serving the Vite build.
    # The login gate is now handled entirely in the frontend JS.
    location / {
        proxy_pass         http://127.0.0.1:${HOST_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           \$http_upgrade;
        proxy_set_header   Connection        'upgrade';
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
NGINXEOF

echo "  Config written."

# ── Test and reload ───────────────────────────────────────────────────────────
echo "[3/3] Testing and reloading nginx..."
nginx -t
systemctl reload nginx

echo ""
echo "======================================"
echo " Done! Nginx config updated."
echo ""
echo " HTTP Basic Auth has been removed."
echo " All /api/* requests are now proxied to the Node API."
echo " Frontend login is handled via JWT in the browser."
echo ""
echo " IMPORTANT: Create at least one user before testing:"
echo "   sudo bash 07_create_user.sh <username> <password> editor"
echo "======================================"
